name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Install dependencies
      run: pnpm install
    - name: Build
      run: pnpm build
    - name: Test
      run: pnpm test
      env:
        CI: true
        BEXIO_CLIENTID: ${{ secrets.BEXIO_CLIENTID }}
        BEXIO_CLIENTSECRET: ${{ secrets.BEXIO_CLIENTSECRET }}
        BEXIO_HOSTNAME: ${{ secrets.BEXIO_HOSTNAME }}
        BEXIO_PASSWORD: ${{ secrets.BEXIO_PASSWORD }}
        BEXIO_USERNAME: ${{ secrets.BEXIO_USERNAME }}
        HOSTNAME: "127.0.0.1"
    - name: Upload coverage
      run: pnpm run report
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
